services:
  randoop:
    container_name: randoop
    build: 
      context: ./geradores/randoop/src
      dockerfile: Dockerfile.java8
    user: "${UID}:${GID}"
    working_dir: /testes-gerados
    command: >
      java -classpath .:/simplesrh/target/classes:/randoop/randoop-all-4.3.3.jar
      randoop.main.Main gentests
      --classlist=/classes.txt
      --time-limit=10
      --junit-package-name=randoop1 
    volumes:
      - ./geradores/randoop/testes-gerados:/testes-gerados
      - ./geradores/randoop/executar-randoop.sh:/executar-randoop.sh
      - ./geradores/randoop/classes.txt:/classes.txt
      - ./projeto/simplesrh:/simplesrh
    env_file:
      - .env.example
    

  evosuite:
    container_name: evosuite
    build: 
      context: ./geradores/evosuite/src
      dockerfile: Dockerfile.java8
    user: "${UID}:${GID}"
    working_dir: /evosuite
    entrypoint: /bin/bash
    volumes:
      - ./geradores/evosuite/testes-gerados:/evosuite
      - ./geradores/evosuite/executar-evosuite.sh:/executar-evosuite.sh
      - ./projeto/simplesrh:/simplesrh
    env_file:
      - .env.example