/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 22:09:25 GMT 2024
 */

package evosuite2.br.ufrn.simplesrh.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufrn.simplesrh.dao.FuncionarioDAO;
import br.ufrn.simplesrh.model.Funcionario;
import br.ufrn.simplesrh.service.FuncionarioService;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FuncionarioService_ESTest extends FuncionarioService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      funcionarioService0.remover("");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      Funcionario funcionario0 = new Funcionario("Gerente", "Gerente", 0.0, (-1));
      funcionarioService0.adicionar(funcionario0);
      assertEquals("Gerente", funcionario0.getCargo());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      doReturn((List<Funcionario>) null).when(funcionarioDAO0).todos();
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      List<Funcionario> list0 = funcionarioService0.todos();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<Funcionario> linkedList0 = new LinkedList<Funcionario>();
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      doReturn(linkedList0).when(funcionarioDAO0).todos();
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      linkedList0.add((Funcionario) null);
      List<Funcionario> list0 = funcionarioService0.todos();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(funcionarioDAO0).todos();
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      // Undeclared exception!
      try { 
        funcionarioService0.buscarPorNome("6q1q");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.ufrn.simplesrh.service.FuncionarioService", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FuncionarioService funcionarioService0 = new FuncionarioService((FuncionarioDAO) null);
      // Undeclared exception!
      try { 
        funcionarioService0.todos();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.ufrn.simplesrh.service.FuncionarioService", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FuncionarioService funcionarioService0 = new FuncionarioService((FuncionarioDAO) null);
      // Undeclared exception!
      try { 
        funcionarioService0.listar();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.ufrn.simplesrh.service.FuncionarioService", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(funcionarioDAO0).todos();
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      List<Funcionario> list0 = funcionarioService0.todos();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(funcionarioDAO0).todos();
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      // Undeclared exception!
      try { 
        funcionarioService0.listar();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<Funcionario> linkedList0 = new LinkedList<Funcionario>();
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      doReturn(linkedList0).when(funcionarioDAO0).todos();
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      linkedList0.add((Funcionario) null);
      funcionarioService0.listar();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Funcionario funcionario0 = new Funcionario("Gerente", "Gerente", 240, 240);
      FuncionarioService funcionarioService0 = new FuncionarioService((FuncionarioDAO) null);
      // Undeclared exception!
      try { 
        funcionarioService0.adicionar(funcionario0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.ufrn.simplesrh.service.FuncionarioService", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FuncionarioDAO funcionarioDAO0 = mock(FuncionarioDAO.class, new ViolatedAssumptionAnswer());
      FuncionarioService funcionarioService0 = new FuncionarioService(funcionarioDAO0);
      Funcionario funcionario0 = new Funcionario();
      // Undeclared exception!
      try { 
        funcionarioService0.adicionar(funcionario0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cargo inv\u00E1lido: null. Os cargos permitidos s\u00E3o: [Analista, Desenvolvedor, Gerente, Coordenador]
         //
         verifyException("br.ufrn.simplesrh.service.FuncionarioService", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FuncionarioService funcionarioService0 = new FuncionarioService((FuncionarioDAO) null);
      // Undeclared exception!
      try { 
        funcionarioService0.remover("N[GN/KePOlp!");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.ufrn.simplesrh.service.FuncionarioService", e);
      }
  }
}
